qwen:
  api_key: sk-
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  models:
    - name: qwen-max
      input_price: 0.000001
      output_price: 0.000004
    - name: qwen-vl-max
      input_price: 0.000002
      output_price: 0.000006
    - name: qwen2.5-vl-72b-instruct
      input_price: 0.1
      output_price: 0.000012
    - name: qwen3-coder-480b-a35b-instruct
      input_price: 0.0021
      output_price: 0.365
    - name: qwen3-235b-a22b-instruct-2507
      input_price: 0.0021
      output_price: 0.365
    - name: qwen3-coder-plus
      input_price: 0.0021
      output_price: 0.365

deepseek:
  api_key: sk-
  base_url: https://api.deepseek.com
  models:
    - name: deepseek-chat
      input_price: 0.000001
      output_price: 0.000004
    - name: deepseek-reasoner
      input_price: 0.000002
      output_price: 0.000006

Moonshot:
  api_key: sk-
  base_url: https://api.moonshot.cn/v1
  models:
    - name: kimi-k2-0711-preview
      input_price: 0.000001
      output_price: 0.000004
    - name: moonshot-v1-8k-vision-preview
      input_price: 0.000002
      output_price: 0.000006
